#+OPTIONS: tex:t
#+TITLE: Methodology Notes
#+AUTHOR: Peter Rayner
* Document Structure
  - will start with an overview as a schematic then perhaps a series
    of descriptions for the components
- Will describe each key point in the process with some suggestions on how we might illustrate it
* Overview of Process
- I imagine a cartoon/schematic for this which I'll try to describe
  - box called Initial estimate, perhaps including a thumbnail map;
    caption: The National Methane Inventory combined with Land Use
    data and other information allows us to produce a map of estimated methane emissions.
  - Arrow leads to box called atmospheric pollution model, we might
    represent it by a weather map with wind arros drawn on it;
    caption: A detailed weather forecast model (WRF) predicts winds which transport methane gas in the
    atmosphere. 
  - Arrow leads to some kind of concentration map; caption: Combining the estimated emissions and an atmospheric pollution model (CMAQ), we generate a
    map of expected atmospheric concentrations of methane - amount of methane in a cubic metre
    of air.
  - Satellite measures a concentration map with the same structure but
    different values (colours?); caption: Satellites can measure the average concentration of methane through the atmosphere.
  - We take the difference between those maps to produce a third map.
    Hot-spots in this difference map drive the alerts; caption: We compare the atmospheric concentrations measured by the satellite with the expected
    atmospheric concentrations produced from the model. These differences will inform corrections
    to the initial emissions estimates. Where these differences are significant, we raise an alert.
  - Arrow leads from this difference map to the atmospheric model
    again, this time with the wind arrows reversed; caption: We can run the atmospheric pollution model backwards to locate the emissions corresponding
    to the concentration differences.
  - Arrow leads back to improved emissions; caption: Corrections produce an improved estimate compared to our initial estimated methane
    emissions.
- Users could perhaps click on any of those boxes to get more information on the steps
  - 
* Initial Emissions Estimates
- Show overall emissions with some grid superimposed, emissions should
  not vary within each grid cell to emphasise the importance of
  resolution. Should perhaps have a large point source in it too.
  Caption: We divide Australia into grid squares and calculate the
  average emission in each. The more grid squares we have the more
  detailed our emission maps but the fewer measurements we have to
  estimate each one.
- How do we estimate emissions? Methane comes from many activities
  and noone surveys each grid square to calculate how much comes from
  each activity in each grid square. Instead they accumulate information on how much the
  activity generates in a region (say Australia or a state) then that
  emission is distributed among grid squares. The national estimate for
  each  activity is, itself, indirect. Instead we estimate or count
  the amount of an activity taking place and multiply by how much
  methane is emitted by each unit of activity. This is described by
  the equation \(E = fA\) where \(E\) is the emission, \(A\) the amount of
  the activity and \(f\) a factor relating activities and emissions. \(f\)
  is called an emission factor. Emission factors must be estimated or
  measured at one place and time then applied elsewhere. Incorrect
  emission factors will lead to incorrect emission estimates. This is
  a major source of uncertainty in methane emissions calculated this way. 
- Sometimes we don't have spatial data for the activity we want but
  can measure a good surrogate. For example the amount of fossil fuel
  burnt in a region is calculated by how much is sold to end-users.
  This can be established by sales statistics and is often well known
  but where people use the fossil fuel is not. Previous research link
  to papers* has shown fossil fuel use is predicted well by the
  intensity of nighttime lights *link to image* which are observed by
  satellites. We can spatialize fossil fuel sources from different
  sectors according to the intensity of nighttime lights.
- we need to calculate the level of confidence we have in the
  emissions inventory. This informs the emissions update process (we
  will be more likely to make corrections where we least trust the
  inventory) but also helps us use the data to answer questions like
  the significance of detected trends. Uncertainties in emissions
  come from uncertainties in activity data, emission factors, regional
  totals, the data we use to spatialize them and the assumption that
  our spatial surrogate is accurate for the emissions sector.
  Uncertainties in numbers like emission factors are particularly
  serious since they may bias emissions in  a region rather than a
  single point. We usually express our confidence in an uncertainty,
  expressed as a standard deviation \(\sigma\). We calculate the
  uncertainty for each point in the inventory by adding the
  uncertainties from each sector. For mathematical reasons we add the
  squares \[\sigma = \sum_{i=1}^N \sigma_i^2\] where \(\sigma_i\) is the
  uncertainty for each sector.
* Atmospheric Pollution Model
- dataflow starts from global weather observations. Most large weather
  agencies generate short-term weather forecasts which they correct
  with satellite and surface observations. This combination of
  forecast and observation produces the best picture of wind,
  temperature and pressure in the atmosphere we have. The agencies run
  these forecasts globally on a mesh or grid. The weather data is
  pixelated at the resolution of the mesh so the finer the mesh the
  better our data. Computational
  restrictions limit these global forecasts to about a 100km mesh which is
  not fine enough for our need. So we run a finer mesh weather model
  called the Weather Research and forecast Model (WRF) in our region
  of interest. We need to know what weather behaviour is coming from
  the outside so we use the global weather models to feed information
  to the edges of our region. *might be good here to show a large mesh
  with a finer mesh inset. Could even show a pressure pattern
  pixelated at the two resolutions.*
- The model produces a snapshot of pressure, wind, temperature and
  moisture every few minutes. It is these wind patterns which move
  gasses like methane around in the atmosphere.
- Calculating a complete picture of the weather every few minutes is
  extremely expensive. Moving gasses around in the atmosphere is
  simpler. We don't need to calculate rainfall or thunderstorms for
  example. So we take the weather data from WRF and use it in an air-pollution
  model, the Community Multi-Scale Air Quality Model (CMAQ). CMAQ can
  also calculate how pollutants are formed and destroyed by chemical
  processes in the atmosphere though for our purposes these processes
  are not very important. *we should discuss that, it's true but
  potentially misleading* 

* Expected Atmospheric Concentrations
- By integrating our Initial Estimate with atmospheric condition models, we create a map indicating expected atmospheric concentrations of methane.
- *IMAGE HERE*
- This visualisation reflects the amount of methane contained in each cubic metre of air across Australia, averaged through the atmosphere.

* Satellite observations

*Picture of satellite*

*Satellite schematic. A bit  like the old slide deck but we'd like to show there's an atmosphere in there and  that we're measuring all through it. For bonus points we could show some kind of plume at the surface caused by an emission and show that we also see all this pollutant higher in the  atmosphere which obscures it*

Satellites measure light or infrared radiation (heat). When they
look at the Earth they see radiation that has passed through the
atmosphere and may have bounced off the surface. Different gases in
the atmosphere absorb different wavelengths (colours) of light. So
if we know or can measure the amount of light at different
wavelengths entering the atmosphere from the Sun, and can measure
how much makes it back out of the atmosphere towards the satellite
we can calculate how much of various gases occur in the atmosphere.
This is a complicated measurement for a number of reasons:

The light may not make it all the way to the surface. If it
bounces off a cloud we may only measure the gas in part of the
atmosphere. We usually don't know how high the cloud is so we
don't know how much of the atmosphere we're measuring and cannot
use these measurements

The light may pass through dust and smoke in the atmosphere. These
also affect the way light travels. While we can correct for small
amounts of these, if there is too much dust or smoke we cannot
calculate the gas amount.

The ground may also absorb different wavelengths differently. We
can correct for this provided we know enough about the surface but
this is not always true

The use of sunlight means we can only measure during the day and
can't measure too close to the poles in winter

If the Sun or the satellite are too low in the sky when viewed
from the place the light strikes the ground then the light is
weaker and more likely to encounter clouds or dust.
So the measurement works best in places with little cloud, not too
close to the poles and without lots of dust pollution. Australia
fits these criteria well.

OpenMethane uses measurements from the Tropospheric Monitoring
Instrument (TROPOMI) *perhaps tooltip saying the troposphere is the
lowest 80% of the atmosphere* on board the sentinel 5 Precursor (S5P)
satellite. S5P orbits the Earth about every 90 minutes at a height of
824 km. It's orbit is oriented almost north-south so passes near both
poles. The orbit is structured so that the satellite stays fixed
relative to the Sun and the Earth rotates beneath it. This is called a
sun-synchronous orbit. It means S5P crosses the equator at the same
local time in every orbit, about 1:30pm travelling from south to north
and 1:30am when travelling from north to south. For half of each orbit
S5P is on the sunny side of the Earth and can take measurements, on
the dark side it cannot. The length of the orbit means there are about
16 orbits each day but these deliberately do not repeat *better
confirm that*  


*Some way of showing satellite grid over Earth, perhaps parallel
lines with arrows for direction and grid lines across them for
along-track sampling.*  The detector on many satellites is like
the detector on a digital camera. One difference is that instead of
capturing an image like a camera, the satellite captures a single
line, usually at right angles to the direction the satellite is travelling. Also like a digital camera the satellite takes time to capture
enough light to produce useful data. All this time the satellite is
travelling over the Earth's surface. Currently the satellite travels
5.6km across the surface of the Earth as it takes each measurement.
Along the line of measurements (perpendicular to the satellite's
path) the satellite designers must decide how much to zoom or pan
the instrument. A zoomed in image has smaller pixels so more
detailed measurements but with a smaller area, leaving parts of the
Earth that may never be measured. The choice of resolution and orbit
mean that TROPOMI potentially sees every point on the globe once per day.

*Impact of clouds etc, adds a cloud mask over previous figure so many
grid cells are blanked out* Earth is, on average, about 50% covered in
cloud. TROPOMI cannot make a methane measurement OpenMethane can use
in cloudy locations. Fortunately clouds move from day to day but some
regions (such as the tropics in the wet season) can stay cloudy for
long periods. Clouds are also usually not continuous so TROPOMI can
often make patchy measurements through breaks in cloud. One trae-off
of the orbit and optical design is that TROPOMI often looks well off
to the side of its orbital track to make a measurement. These
measurements are at high light angles so the chance of being
intercepted by a cloud is increased. TROPOMI also cannot make a
measurement when there is too much smoke or dust in the atmosphere. It
also cannot make many measurements over water. For these reasons only a
few percent of the total TROPOMI measurements are available but this
still leaves *around 50,000* measurements available over
Australia each day.

When a pollutant like methane enters the atmosphere it usually spreads
horizontally and vertically in a characteristic plume. *perhaps show
figure* It will gradually mix with plumes from other sources and the
background of methane already in the atmosphere. Thus we would like to
identify each plume at its most concentrated and distinct. Satellite
instruments are good at this because they observe so many locations
but they do suffer from measuring methane through the whole atmosphere. Thus even when
measuring near the source of the plume it is diluted by the background
of methane already present.

Every measurement is uncertain. This is particularly clear with
satellites where what they measure (radiation arriving at their
detectors) is not what they wish to infer (e.g. methane concentration
in the atmosphere several hundred kms beneath them). There is an
algorithm which links the two. This algorithm is based on
well-understood physics but, as already mentioned, other aspects of
the atmosphere and surface can affect the satellite measurements. the
algorithm that calculates methane concentration also calculates an
uncertainty on that measurement. We check both the measurements and
uncertainties by comparing satellite measurements with a network of
ground stations which can themselves be checked against absolute
standards. this traceability of measurements to absolute standards is
critical for confidence in detection and for being able to use
multiple different instruments.
* Alerts
OpenMethane publishes notifications when measured methane
concentration are significantly different from what is expected. We
calculate the expected value by combining our emissions inventory with
the air pollution model. This creates a forecast of the expected
methane concentration for every hour of every day. By carefully
sampling the model forecast in exactly the same way as the satellite
samples the atmosphere we can compare our expected value with what we
measure. We can only do this where the satellite makes an observation
so much of Australia will be unavailable on a single day. It is
important to remember that absence of data does not imply support for
the emissions inventory, simply that we cannot observe it.

Care is also needed when deciding what is a significant difference
between expected and measured values. Concentrations vary naturally as
winds move methane from different sources around in the atmosphere. In
principle we can predict all these variations with CMAQ but no model
is perfect so we will certainly fail to capture some variations. These
variations will be larger near strong sources of methane. Similarly
there is an uncertainty in the satellite measurements. So we apply a
significance threshold for events:
\[\|\mbox{expected} -\mbox{observed}\| > 2\sigma\].
\(\sigma\), our total uncertainty comprises the natural variation and
satellite uncertainty:
\[\sigma = [\sigma_v^2 +\sigma_s^2]^{0.5}\] where \(\sigma_v\) is the
uncertainty due to natural variation and \(\sigma_s\) is the
uncertainty due to satellite measurements. this threshold will be
refined with experience.
We also cross-check significant uncertainties for potential problems
with the satellite data such as incorrect environmental factors.

There is a difference between the resolution of the concentration  map
produced by CMAQ (25\(\times\)25 km) and the satellite observations (5.6\(\times\)7.2
km). This means we may see concentration events occurring at
a particular part of a model pixel due to the location of an emission
within the pixel. This is both useful and problematic. It is useful
because it can give guidance on where to look for the source of an
event. It is problematic because CMAQ can only relate average
emissions in pixels to average concentrations in pixels. If we measure
an uneven distribution of satellite pixels within a CMAQ pixel we
could bias this average. This is a serious problem with networks of
fixed stations but we also need to account for it in satellite data.
We include this as an extra uncertainty in how well we expect our
model concentrations to match the satellite data. 
* Emissions Correction
Once we have accounted for possible uncertainties in the satellite
data and the capability of our models, we assume that other mismatches
between expected and observed concentrations are caused by errors in
our emissions inventory. Our task is to work backwards from the
concentration mismatches to work out where and how much to correct the
emissions. We do this by effectively running the atmospheric pollution
model backwards. remember that the satellite measures through the
whole atmosphere and that the wind distributes methane from an
emission in three dimensions. Thus we need to backtrack concentration
differences through the atmosphere, not just at the surface. *Show difference plot
from alerts step and wind map with arrows reversed* Applying these
corrections from all the concentration mismatches together and
accounting for all the changes in wind direction over a month we can
produce a corrected map of the emissions inventory. *Arrows leading backwards from high differences to show increased emissions*

*not sure about this last para*
One incorrect emission will hopefully generate several concentration
mismatches so that we have multiple cross-checks on the location and
size of any error. However the problems with clouds and dust we noted
earlier may also mean that some emissions are incorrect but don't have
satellite observations to point out the error. As with the events
discussed earlier, the absence of correction to an emission could mean
either that the satellite observations confirm the emissions inventory
or that we lack observations to check it. We can check this with a
series of "what if" experiments. We vary the emissions randomly and
calculate the expected concentrations that the satellite would
observe. If significant differences in concentration are observable in
this counter-factual world we can be confident that we would observe
real differences. On the other hand, if emission differences do not
yield changes in model concentrations (usually because of cloud) then
we cannot be confident in our update to the emissions inventory in
that region.
