name: Cleanup old docker containers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # run every day at midnight, utc

jobs:
  delete-package-versions:
    name: Delete PR images older than 2 weeks
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: openmethane
          # Token with delete:packages scope
          # TODO: Migrate to an org GitHub App with the same permissions
          token: ${{ secrets.PAT }}
          image-names: openmethane
          image-tags: "pr-* !latest"
          tag-selection: both  # select both tagged and untagged package versions
          cut-off: 2w
          dry-run: true
